sourcekitten_sourcefile:
  - sourcekitten/SotoCore.json
author_url: https://github.com/soto-project
github_url: https://github.com/soto-project/soto-core
copyright: '© Copyright (c) 2020 Soto project authors'
readme: README.md
