language: generic

matrix:
  include:
    - os: linux
      services: docker
      before_install:
        - docker pull swift:4.2
      script:
        - docker run -v "$(pwd):/root/aws-sdk-swift-core" swift:4.2 /bin/sh -c "cd /root/aws-sdk-swift-core && swift build && swift test -Xswiftc -DDEBUG"
    - os: osx
      osx_image: xcode10.2
      script:
        - brew install libressl
        - swift build
        - swift test -Xswiftc -DDEBUG

