# run this with docker-compose -f docker/docker-compose.yml run test
version: "3.3"

services:
  common: &common
    build: .
    volumes:
      - ..:/working
    working_dir: /working

  test:
    <<: *common
    command: /bin/bash -xcl "swift test --enable-test-discovery -Xswiftc -g"

  test-amazon:
    build:
        context: .
        dockerfile: Dockerfile.amazon
    volumes:
      - ..:/working
    working_dir: /working
    command: /bin/bash -xcl "swift test --enable-test-discovery -Xswiftc -g"

  test-thread:
    <<: *common
    command: /bin/bash -xcl "swift test --enable-test-discovery --sanitize=thread -Xswiftc -g"

  test-address:
    <<: *common
    command: /bin/bash -xcl "swift test --enable-test-discovery --sanitize=address -Xswiftc -g"

  test-release:
    <<: *common
    command: /bin/bash -xcl "swift test --enable-test-discovery --sanitize=address -c release -Xswiftc -enable-testing"

  clean:
    <<: *common
    command: /bin/bash -xcl "swift package clean"

  shell:
    <<: *common
    entrypoint: /bin/bash
