name: CI

on:
  push:
    branches:
    - "*"
  schedule:
    - cron:  '0 9 * * 2'

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['swiftlang/swift:nightly-5.2']
    container:
      image: ${{ matrix.image }}
      volumes:
      - $GITHUB_WORKSPACE:/src
      options: --workdir /src
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        apt-get update -qq
        apt-get install -q -y tzdata libssl-dev zlib1g-dev
    - name: Build
      run: swift build
    - name: Test
      run: swift test --parallel --enable-test-discovery
