name: Sanity Check

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  sanity-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install SwiftFormat
      uses: Cyberbeni/install-swift-tool@v2
      with:
        url: https://github.com/nicklockwood/SwiftFormat
        branch: '0.47.4'
    - name: run script
      run: ./scripts/sanity.sh
