name: Swift

on: 
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

env:
  CODECOV_TOKEN: ${{ secrets. CODECOV_TOKEN }}

jobs:
  macos:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: SPM build
      run: swift build
    - name: SPM tests
      run: swift test
    - name: Generate xcode project
      run: swift package generate-xcodeproj
    - name: Xcode tests
      run: xcodebuild -quiet -parallel-testing-enabled YES -scheme AWSSDKSwiftCore-Package -enableCodeCoverage YES build test
    - name: Upload to codecov.io
      run: bash <(curl -s https://codecov.io/bash) -J 'AWSSDKSwiftCore' 

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['5.0', '5.1']
    container:
      image: swift:${{ matrix.tag }}
      volumes:
      - $GITHUB_WORKSPACE:/src
      options: --workdir /src
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        apt-get update -qq
        apt-get install -q -y tzdata libssl-dev zlib1g-dev
    - name: Test
      run: swift test --parallel --enable-code-coverage
      if: matrix.tag < 5.1
    - name: Test
      run: swift test --parallel --enable-code-coverage --enable-test-discovery
      if: matrix.tag >= 5.1
    - name: Convert coverage files
      run: llvm-cov export -format="lcov" .build/debug/AWSSDKSwiftCorePackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
      if: matrix.tag >= 5.1
    - name: Upload to codecov.io
      run: bash <(curl -s https://codecov.io/bash) -J 'AWSSDKSwiftCore' 
      if: matrix.tag >= 5.1